"""added car to the  table

Revision ID: 06ce8fdbf5ba
Revises: 681a3ef91d32
Create Date: 2024-01-11 11:54:25.195426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ce8fdbf5ba'
down_revision = '681a3ef91d32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('clients_id', sa.Integer(), nullable=True))
    op.add_column('cars', sa.Column('employees_id', sa.Integer(), nullable=True))
    op.drop_column('cars', 'client_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('client_id', sa.INTEGER(), nullable=True))
    op.drop_column('cars', 'employees_id')
    op.drop_column('cars', 'clients_id')
    # ### end Alembic commands ###
