"""added employee table

Revision ID: 170342a67904
Revises: a3c1f5caef0a
Create Date: 2024-01-10 13:21:22.207993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '170342a67904'
down_revision = 'a3c1f5caef0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('contact', sa.Integer(), nullable=True),
    sa.Column('cars_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cars_id'], ['cars.id'], name=op.f('fk_employees_cars_id_cars')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    # ### end Alembic commands ###
