"""added car to the  table

Revision ID: 2bdb2d73bd91
Revises: 3bb2c05eea01
Create Date: 2024-01-11 12:14:46.542431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bdb2d73bd91'
down_revision = '3bb2c05eea01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
