"""added car to the  table

Revision ID: 3bb2c05eea01
Revises: a2e31068eb33
Create Date: 2024-01-11 12:10:05.497566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bb2c05eea01'
down_revision = 'a2e31068eb33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
