"""added car to the  table

Revision ID: 681a3ef91d32
Revises: da5465a5294b
Create Date: 2024-01-11 11:52:42.075261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '681a3ef91d32'
down_revision = 'da5465a5294b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('client_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'client_id')
    # ### end Alembic commands ###
