"""ammended the parameters in clients table

Revision ID: 9a6d0d47398e
Revises: 2bdb2d73bd91
Create Date: 2024-01-12 15:58:50.857293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a6d0d47398e'
down_revision = '2bdb2d73bd91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
