"""added car to the  table

Revision ID: a2e31068eb33
Revises: 06ce8fdbf5ba
Create Date: 2024-01-11 12:06:58.416716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2e31068eb33'
down_revision = '06ce8fdbf5ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
