"""added client table

Revision ID: a3c1f5caef0a
Revises: b1f63b9fcbc6
Create Date: 2024-01-10 13:20:34.290210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3c1f5caef0a'
down_revision = 'b1f63b9fcbc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('cars_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cars_id'], ['cars.id'], name=op.f('fk_clients_cars_id_cars')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    # ### end Alembic commands ###
