"""ammended the parameters in clients table

Revision ID: c773d5c1647c
Revises: 9a6d0d47398e
Create Date: 2024-01-12 16:02:39.041179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c773d5c1647c'
down_revision = '9a6d0d47398e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
