"""added eployees contact to the  table

Revision ID: da5465a5294b
Revises: 170342a67904
Create Date: 2024-01-11 11:42:43.505664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da5465a5294b'
down_revision = '170342a67904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('contact', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'contact')
    # ### end Alembic commands ###
